### ISSUE TITLE
cannot connect?

### ISSUE THREAD

**Issue by modyamash** [The-SourceCode/SourceBot.net#16]
Starting website...
(node:228) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.    
Database connection error!
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoError: Authentication failed.
    at E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\auth\auth_provider.js:46:25
    at E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\auth\scram.js:240:11
    at _callback (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connect.js:320:5)
    at Connection.messageHandler (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connect.js:349:5)     
    at Connection.emit (events.js:321:20)
    at processMessage (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connection.js:384:10)
    at Socket.<anonymous> (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connection.js:553:15)        
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:280:11)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\topologies\server.js:433:11)
    at Pool.emit (events.js:321:20)
    at E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\pool.js:577:14
    at E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\pool.js:1007:11
    at callback (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connect.js:93:5)
    at E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connect.js:367:21
    at E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\auth\auth_provider.js:66:11
    at E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\auth\scram.js:240:11
    at _callback (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connect.js:320:5)
    at Connection.messageHandler (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connect.js:349:5)     
    at Connection.emit (events.js:321:20)
    at processMessage (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connection.js:384:10)
    at Socket.<anonymous> (E:\New folder\SourceBot.net-master\node_modules\mongodb\lib\core\connection\connection.js:553:15)        
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:280:11)

**Comment by Jacxk** [comment]
make sure your mongo credentials are correct

**Comment by modyamash** [comment]
> make sure your mongo credentials are correct

iknow i tryed to connect via localhost but i got Database connection error!
and also tryed to connect via mongo cloud alts Database connection error!
please if thereway to connect with you i can send  you screenshots  
and  see if i made  smth worng :) I have been trying to database connect for more than five days
please help me  :) thank you

**Comment by Jacxk** [comment]
Try adding `{ useUnifiedTopology: true } ` to the connection option param 
https://github.com/The-SourceCode/SourceBot.net/blob/master/database/connector.js line 6

**Comment by modyamash** [comment]
> Try adding `{ useUnifiedTopology: true } ` to the connection option param
> https://github.com/The-SourceCode/SourceBot.net/blob/master/database/connector.js line 6

done this my config file 
// To make this work you must clone it and rename it to "config.js"

module.exports = {
    mongo: {
        ip: "mongodb+srv:admin:1234>@sourcebot-rwjch.gcp.mongodb.net/test?retryWrites=true&w=majority",
        user: "admin",
        pwd: "1234",
        port: "27017",
        db: "sourcebot",
        collections: {
            userData: "UserData",
            incidents: "IncidentReports"
        }
    },
    ratelimiter: {
        time: 1000, // time in ms
        amount: 10 // amount of requests per {time}
    },
    PORT: 1234,
    bot_token: "NjI2MTgzODc4MDEyNDM2NDgx.XiD8WQ.Q6vRQBIR5Z_EOAj4dPwe3CU_W7I", // to get user's discord data.
    autodeploy: {
        branch: "production", // branch to auto deploy
        secret: "" // secret keywords for github's webhooks
    },
    underConstruction: false,
    discord: {
        guild_id: "" // ID of the guild
    }
};
and this my mongodb alts connection
also i tryed localhost but same problem !
this is log
Starting website...
Database connection error!
TypeError: callback is not a function
    at E:\New folder\SourceBot.net-master\node_modules\mongoose\lib\connection.js:786:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async connect (E:\New folder\SourceBot.net-master\database\connector.js:6:5)
---
iknow you taird form me but need little help i'm so sorry for that :(

**Comment by Jacxk** [comment]
The `ip` is wrong, you're passing a connection url, you need to pass the url/ip like `localhost` or `test.com`  
Also, you might want to reset you token and credentials.

**Comment by modyamash** [comment]
> The `ip` is wrong, you're passing a connection url, you need to pass the url/ip like `localhost` or `test.com`
> Also, you might want to reset you token and credentials.

thankk you for your help now database is connected but, 
its stuck on database connected and nothing happend :/
---------
E:\New folder\SourceBot.net-master> npm start  

> sourcebot@2.0.0 start E:\New folder\SourceBot.net-master
> echo Starting website... && node ./bin/www

Starting website...
Database connected!

**Comment by Jacxk** [comment]
You should be good now
Use the `localhost:<PORT>`, the port should be located on the config

**Comment by modyamash** [comment]
i have change loginway cuz all ways old connection wasn't want to connect! i create this ! look
------
module.exports = {
    mongo: {
        URI:"mongodb://admin:1234@sourcebot-shard-00-00-rwjch.gcp.mongodb.net:27017,sourcebot-shard-00-01-rwjch.gcp.mongodb.net:27017,sourcebot-shard-00-02-rwjch.gcp.mongodb.net:27017/test?authSource=admin&replicaSet=sourcebot-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true",
        collections: {
            userData: "UserData",
            incidents: "IncidentReports"
        }
    },
    ratelimiter: {
        time: 1000, // time in ms
        amount: 10 // amount of requests per {time}
    },
----
connector=
----
const mongoose = require('mongoose');
const {URI} = require('../config').mongo;

// connect to database and catch errors
async function connect() {
    await mongoose.connect(URI, {
    useUnifiedTopology: true,
    useNewUrlParser: true
  });
}

connect().then(() => {
    global.connected = true;
    console.log("Database connected!");
}).catch(e => {
    console.error("Database connection error!")
    global.connected = false;
});
-----
i'm little bit not good deve at all but i'm leaning for the teachers like you :)

**Comment by Jacxk** [comment]
That also works, glad you got it working

**Comment by modyamash** [comment]
> That also works, glad you got it working

thank you boss,
But it gets stuck after this process, Bot does not work
Are there things to do in the database collections?, I just did them and didn't do anything to them after that!
If there is something else to do in the database collections, please explain it to me, I am a little weak
Thanks for this beautiful patience

**Comment by Jacxk** [comment]
I think you got the wrong repository, because this repo is for https://sourcebot.net/
